---
title: "async/await"
---
# 従来の非同期処理の書き方の問題点
```swift
func fetchBookReview(
        id: String,
        token: String
    ) {
        let headers = ["Authorization": "Bearer \(token)"]
        let endpoint = "/books/\(id)"
        
        TechTrainAPIClient.shared.makeRequest(to: endpoint, method: "GET", body: nil, headers: headers) { result in
            switch result {
            case .success(let data):
                do {
                    let decoder = JSONDecoder()
                    let bookReview = try decoder.decode(BookReview.self, from: data)
                    completion(.success(bookReview))
                } catch {
                    completion(.failure(.underlyingError(.decodingError)))
                }
            case .failure(let error):
                completion(.failure(error.toServiceError()))
            }
        }
    }
```
## 問題 1: ネストが深くなりやすい
非同期処理をコールバックで書くと、ネストが深くなり、可読性が下がる。
## 問題 2: エラーハンドリングが分散
従来のCompletion Handlerでは、エラー処理が各コールバックに分散する。
## 問題 3: データの競合が起きる可能性がある
競合は、複数の処理が同時に同じデータを使い、「読み取り」や「書き込み」が重なるときに起こる。例えば、カウンターの値を1ずつ増やす処理で、2つの処理が同時に現在の値「0」を読み取った場合、それぞれが「0 + 1 = 1」と計算し、結果を上書きする。この結果、「2」が期待されているが「1」となる、という問題が発生する。
# Swift Concurrency
## 1. async/await
- `async`: 非同期処理を扱う関数を定義する
- `await`: 非同期処理の結果を待つ

この仕組みで、従来のコールバックを使った複雑なコードがシンプルになる。

```swift: BookReviewService.swift
func fetchBookReview(
        id: String,
        token: String
    ) async throws(TechTrainAPIError.ServiceError) -> BookReview {
        let endpoint = "/books/\(id)"
        let headers = ["Authorization": "Bearer \(token)"]
        
        do {
            let bookReviewData = try await TechTrainAPIClient.shared.makeRequestAsync(to: endpoint, method: "GET", headers: headers, body: nil)
            let decodedBookReview = try BookReview.decodeBookReview(bookReviewData)
            return decodedBookReview
        } catch {
            throw error.toServiceError()
        }
    }
```